const feedbackFrames = (kind: 'perfect' | 'good' | 'miss'): readonly string[] =>
  Array.from({ length: 20 }, (_, index) => {
    const number = index + 1;
    const frame = number < 10 ? `000${number}` : `00${number}`;
    return `bottlehero/feedback/${kind}/${frame}`;
  });

/** Cocos resources 路径（无扩展名） */
const res = (relativePath: string): string => {
  const normalized = relativePath.replace(/^\//, '').replace(/\.[^/.]+$/, '');
  return `bottlehero/${normalized}`;
};

/** 与 BottleHeroMvp 主流程一致的 Web 相对路径（带扩展名，用于 sfx 键名等） */
export const bottleHeroWebPaths = {
  comboDigits: [
    'ui/digits/num_0.png',
    'ui/digits/num_1.png',
    'ui/digits/num_2.png',
    'ui/digits/num_3.png',
    'ui/digits/num_4.png',
    'ui/digits/num_5.png',
    'ui/digits/num_6.png',
    'ui/digits/num_7.png',
    'ui/digits/num_8.png',
    'ui/digits/num_9.png',
  ] as const,
  stagedThrowItems: [
    'gameplay/throw-items/level_01/throw_item_00_kettle.png',
    'gameplay/throw-items/level_01/throw_item_01_toy.png',
    'gameplay/throw-items/level_01/throw_item_02_toy.png',
    'gameplay/throw-items/level_01/throw_item_03_car.png',
    'gameplay/throw-items/level_01/throw_item_04_car.png',
    'gameplay/throw-items/level_01/throw_item_05_car.png',
    'gameplay/throw-items/level_01/throw_item_06_car.png',
    'gameplay/throw-items/level_01/throw_item_07_car.png',
    'gameplay/throw-items/level_01/throw_item_08_car.png',
    'gameplay/throw-items/level_01/throw_item_09_tv.png',
    'gameplay/throw-items/level_01/throw_item_10_tv.png',
    'gameplay/throw-items/level_01/throw_item_11_tire.png',
    'gameplay/throw-items/level_01/throw_item_12_tire.png',
    'gameplay/throw-items/level_01/throw_item_13_rocket_01.png',
    'gameplay/throw-items/level_01/throw_item_14_rocket_02.png',
    'gameplay/throw-items/level_01/throw_item_15_rocket_03.png',
    'gameplay/throw-items/level_01/throw_item_16_rocket_04.png',
    'gameplay/throw-items/level_01/throw_item_17_ship_01.png',
    'gameplay/throw-items/level_01/throw_item_18_ship_02.png',
    'gameplay/throw-items/level_01/throw_item_19_satellite_01.png',
    'gameplay/throw-items/level_01/throw_item_20_satellite_02.png',
    'gameplay/throw-items/level_01/throw_item_21_satellite_03.png',
    'gameplay/throw-items/level_01/throw_item_22_satellite_04.png',
    'gameplay/throw-items/level_01/throw_item_23_satellite_05.png',
    'gameplay/throw-items/level_01/throw_item_24_satellite_06.png',
    'gameplay/throw-items/level_01/throw_item_25_satellite_07.png',
    'gameplay/throw-items/level_01/throw_item_26_satellite_08.png',
  ] as const,
  sfx: [
    'audio/recover_stability.m4a',
    'audio/timing_item_bomb.m4a',
    'audio/button.m4a',
    'audio/avatar_home_bgm.m4a',
    'audio/boss_fighting_bgm.mp3',
    'audio/boss_warning.mp3',
    'audio/boss_bullet_attack.mp3',
    'audio/boss_hitted.mp3',
    'audio/boss_frozened.mp3',
    'audio/boss_dead.mp3',
    'audio/reward_icon.mp3',
  ] as const,
} as const;

export const BottleHeroAssets = {
  textures: {
    levelBackground: res('backgrounds/level_01/level_01_start'),
    loopBackground: res('backgrounds/level_01/level_01_loop'),
    titleBackground: res('backgrounds/level_01/level_01_start'),
    scene03BridgeBackground: res('backgrounds/level_01/level_01_scene_03_bridge'),
    scene03LoopBackground: res('backgrounds/level_01/level_01_scene_03_loop'),
    scene04BridgeBackground: res('backgrounds/level_01/level_01_scene_04_bridge'),
    scene04LoopBackground: res('backgrounds/level_01/level_01_scene_04_loop'),
    logo: res('ui/logo'),
    buttonNormal: res('ui/buttons/start_normal'),
    buttonPressed: res('ui/buttons/start_pressed'),
    enterButton: res('ui/buttons/enter_button'),
    continueButton: res('ui/buttons/continue_button'),
    quitButton: res('ui/buttons/quit_button'),
    playGameButton: res('ui/buttons/play_game'),
    timingBar: res('timing/timing_bar_line'),
    timingBarCircle: res('timing/timing_bar_circle'),
    timingBarTriangle: res('timing/timing_bar_triangle'),
    timingBarPath: res('timing/timing_bar_path'),
    timingBarStar: res('timing/timing_bar_star'),
    timingBarInfinity: res('timing/timing_bar_Infinity symbol'),
    timingHandle: res('timing/timing_handle'),
    timingPoint: res('timing/timing_point'),
    timingPointNormal: res('timing/timing_point_normal'),
    timingPointGood: res('timing/timing_point_good'),
    timingPointRare: res('timing/timing_point_rare'),
    timingPointTreasure: res('timing/timing_point_treasure'),
    playerArm: res('player/paw_right'),
    catNpc: res('player/cat_helper'),
    comboBar: res('ui/hud/combo_bar'),
    scorePanel: res('ui/hud/score_panel'),
    gameOverPanel: res('ui/hud/gameover_panel'),
    stabilityBar: res('ui/hud/stability_bar'),
    stabilityState: res('ui/hud/stability_state'),
    bottles: [
      res('items/bottle_02'),
      res('items/bottle_03'),
      res('items/bottle_04'),
      res('items/bottle_05'),
      res('items/bottle_06'),
    ],
    stagedThrowItems: bottleHeroWebPaths.stagedThrowItems.map(res),
    comboDigits: bottleHeroWebPaths.comboDigits.map(res),
  },
  audio: {
    bgm: res('audio/bgm'),
    throw: res('audio/throw'),
    perfect: res('audio/perfect'),
    good: res('audio/good'),
    miss: res('audio/miss'),
    button: res('audio/button'),
    avatarHomeBgm: res('audio/avatar_home_bgm'),
    bossFightingBgm: res('audio/boss_fighting_bgm'),
    bossWarning: res('audio/boss_warning'),
    bossBulletAttack: res('audio/boss_bullet_attack'),
    bossHitted: res('audio/boss_hitted'),
    bossFrozened: res('audio/boss_frozened'),
    bossDead: res('audio/boss_dead'),
    recoverStability: res('audio/recover_stability'),
    timingItemBomb: res('audio/timing_item_bomb'),
    rewardIcon: res('audio/reward_icon'),
  },
  feedback: {
    perfect: feedbackFrames('perfect'),
    good: feedbackFrames('good'),
    miss: feedbackFrames('miss'),
  },
} as const;
